---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Pull and Up docker
      community.docker.docker_compose:
        project_src: /home/ec2-user/
        pull: true
      vars:
        ansible_python_interpreter: /usr/bin/python3