---
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 60
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: yes
    - name: Start docker
      ansible.builtin.service:
        name: docker
        state: started
    - name: Enable docker
      ansible.builtin.service:
        name: docker
        enabled: yes
    - name: Add the user 'ec2-user' to the group docker
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Install docker compose
      pip:
        name: docker-compose>1.7.0,<2.0.0
        executable: pip3
    - name: Copy compose.yaml to machine
      ansible.builtin.copy:
        src: ../compose.yaml
        dest: /home/ec2-user/compose.yaml
        owner: ec2-user
        group: ec2-user
        mode: '0744'